apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
{{- include "mychart.labels" . | indent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        {{- include "mychart.labels" . | indent 4 }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.17
          ports:
            - containerPort: 80