{{- define "mychart.labels" }}
  labels:
    generator: helm
    date: {{ now | htmlDate }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  {{- template "mychart.labels" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      {{- template "mychart.labels" }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.17
          ports:
            - containerPort: 80